# Site settings
title: Rui.H's House
header-img: img/home-bg.jpg
email: huangrui27@icloud.com
description: "Rui.H's House growth thoughts"
baseurl: ""
url: "http://hrlty.github.io/"
twitter_username: ShrekTheWizard
github_username:  hrlty
facebook_username:  ruihuang988

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
